### ISSUE TITLE
Infill_Maximal_Distance line 5 Error

### ISSUE THREAD

**Issue by swayne1** [zhandawei/Multiobjective_EGO_algorithms#3]
"Error using repmat
Replication factors must be a row vector of integers or integer scalars."

The following line is giving the above error whenever the Infill_Maximal_Distance function is called:
obj(ii,:) = -min(sum((repmat(x(ii, :),size(sample_x),1) - sample_x).^2,2));

I changed it slightly and now it seems to be working fine:
obj(ii,:) = -min(sum((repmat(x(ii, :),[size(sample_x,1),1]) - sample_x).^2,2));

**Comment by zhandawei** [comment]
It has been fixed. Thanks a lot.
